# Generated by Django 2.2 on 2020-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Next_app', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attach_file',
            field=models.CharField(default=models.FileField(blank=True, null=True, upload_to='images/'), max_length=20),
        ),
    ]
