# Generated by Django 2.2 on 2020-11-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Next_app', '0003_auto_20201124_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description_title', models.TextField(max_length=20)),
                ('description', models.CharField(max_length=60)),
                ('teacher_image', models.ImageField(upload_to='images/')),
                ('programme_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='attach_file',
            field=models.FileField(upload_to='notice/'),
        ),
    ]
