# Generated by Django 2.2 on 2020-11-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Next_app', '0004_auto_20201124_1950'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programme',
            table='Programme',
        ),
    ]
