# Generated by Django 2.2 on 2020-11-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Next_app', '0005_auto_20201125_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programme',
            new_name='Pro',
        ),
        migrations.AlterModelTable(
            name='pro',
            table='Pro',
        ),
    ]
