# Generated by Django 2.2 on 2020-11-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Next_app', '0006_auto_20201125_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pro',
        ),
    ]
